export type GalleryItem =
  | { type: "photo"; url: string; alt?: string }
  | { type: "video"; vimeoId: string; vimeoHash?: string; poster?: string };

export interface Massagista {
  slug: string;
  name: string;
  city: string;
  state: string;
  neighborhood?: string;
  gender: string;
  attends: string;
  paymentMethods: string[];
  schedule: string;
  comments: number;
  views: number;
  viewsToday: number;
  announcedSince: string;
  updatedAt: string;
  noSexualInteraction: boolean;
  whatsapp: string;
  whatsappDisplay: string;
  profilePhoto: string;
  gallery: GalleryItem[];
  description: string;
  online: boolean;
  videoCount: number;
  postedAgo: string;
  delay: string;
  cardOrder: number;
}

export const MASSAGISTAS: Massagista[] = [
  {
    slug: "sophia-mcz",
    name: "Sophia",
    city: "Maceió",
    state: "AL",
    neighborhood: "Ponta Verde",
    gender: "Feminino",
    attends: "Homens, Mulheres",
    paymentMethods: ["Cartão de Crédito", "Cartão de Débito", "PIX", "Dinheiro"],
    schedule: "09h às 19h",
    comments: 4,
    views: 12480,
    viewsToday: 38,
    announcedSince: "2 anos 4 meses",
    updatedAt: "há 2 minutos",
    noSexualInteraction: true,
    whatsapp: "5582988709008",
    whatsappDisplay: "82 98870-9008",
    profilePhoto: "/assets/16549_b05c61c7f417.webp",
    gallery: [
      { type: "photo", url: "/assets/16549_b05c61c7f417.webp" },
      { type: "video", vimeoId: "20784267", vimeoHash: "bafedaddf9" },
      { type: "photo", url: "/assets/agata-capa0405_b1f62b6526d3.webp" },
      { type: "photo", url: "/assets/heloisaferraz-capa1211_2bad55f9a76b.webp" },
      { type: "video", vimeoId: "25546879", vimeoHash: "10de44524b" },
      { type: "photo", url: "/assets/img_3601_b06a0c98e448.webp" },
    ],
    description:
      "✨ Cuide do seu corpo e da sua mente com a massoterapia! Você sabia que a massagem vai muito além de um momento de lazer? Ela é uma prática terapêutica que alivia tensões, melhora a circulação sanguínea, reduz o estresse e proporciona um sono mais tranquilo. Ofereço atendimentos personalizados, com técnicas adaptadas às necessidades de cada pessoa: relaxamento muscular, alívio de dores crônicas, melhora da flexibilidade, equilíbrio emocional. Cada sessão é preparada para você se sentir renovado(a) e com mais qualidade de vida. Não deixe o cuidado com você para depois! Agende já o seu horário e presenteie-se com o bem-estar que você merece. 🌿💖",
    online: true,
    videoCount: 3,
    postedAgo: "Há 2 minutos",
    delay: "delay-1",
    cardOrder: 1,
  },
  {
    slug: "anne-aju",
    name: "Anne Massoterapeuta",
    city: "Aracaju",
    state: "SE",
    neighborhood: "Atalaia",
    gender: "Feminino",
    attends: "Homens",
    paymentMethods: ["PIX", "Dinheiro"],
    schedule: "10h às 22h",
    comments: 12,
    views: 8920,
    viewsToday: 22,
    announcedSince: "1 ano 8 meses",
    updatedAt: "há 5 minutos",
    noSexualInteraction: true,
    whatsapp: "5579988709008",
    whatsappDisplay: "79 98870-9008",
    profilePhoto: "/assets/whatsapp-image-2026-05-07-at-1_c0e99e981931.webp",
    gallery: [
      { type: "photo", url: "/assets/whatsapp-image-2026-05-07-at-1_c0e99e981931.webp" },
      { type: "video", vimeoId: "20972562", vimeoHash: "e6cf03be96" },
      { type: "photo", url: "/assets/whatsapp-image-2026-04-28-at-1_460c980ee5ed.webp" },
      { type: "photo", url: "/assets/whatsapp-image-2026-02-20-at-1_48d22c4db28f.webp" },
    ],
    description:
      "🌹 Sou Anne, massoterapeuta certificada com mais de 5 anos de experiência. Ofereço sessões de massagem relaxante, terapêutica e tântrica em ambiente discreto e aconchegante na Atalaia. Trabalho com técnicas que aliviam dores, reduzem o estresse e renovam a energia. Atendimento exclusivo, com toda privacidade e profissionalismo. Agende seu horário e descubra o poder do toque sutil. 💆‍♂️✨",
    online: true,
    videoCount: 2,
    postedAgo: "Há 2 horas",
    delay: "delay-2",
    cardOrder: 2,
  },
  {
    slug: "danny-ssa",
    name: "Danny",
    city: "Salvador",
    state: "BA",
    neighborhood: "Pituba",
    gender: "Feminino",
    attends: "Homens, Mulheres, Casais",
    paymentMethods: ["Cartão de Crédito", "Cartão de Débito", "PIX", "Dinheiro"],
    schedule: "08h às 22h",
    comments: 28,
    views: 22150,
    viewsToday: 86,
    announcedSince: "3 anos 1 mês",
    updatedAt: "há 12 minutos",
    noSexualInteraction: true,
    whatsapp: "5571988709008",
    whatsappDisplay: "71 99319-0432",
    profilePhoto: "/assets/4291cec9-6e6d-4031-b150-1ccb94_1ddd2944badf.webp",
    gallery: [
      { type: "photo", url: "/assets/4291cec9-6e6d-4031-b150-1ccb94_1ddd2944badf.webp" },
      { type: "video", vimeoId: "29158045", vimeoHash: "66046799a3" },
      { type: "photo", url: "/assets/samanta-massagens130125_e128889fee88.webp" },
      { type: "photo", url: "/assets/ray-massoterapeuta_c745ad6158b1.webp" },
      { type: "video", vimeoId: "20784267", vimeoHash: "bafedaddf9" },
      { type: "photo", url: "/assets/img_1396_5134059c329a.webp" },
      { type: "photo", url: "/assets/heloisaferraz-capa1211_2bad55f9a76b.webp" },
    ],
    description:
      "🔥 Cuide do seu corpo e da sua mente com a massoterapia! Você sabia que a massagem vai muito além de um momento de lazer? Ela é uma prática terapêutica que alivia tensões, melhora a circulação sanguínea, reduz o estresse e proporciona um sono mais tranquilo. Ofereço atendimentos personalizados, com técnicas adaptadas às necessidades de cada pessoa: relaxamento muscular, alívio de dores crônicas, melhora da flexibilidade, equilíbrio emocional. Cada sessão é preparada para você se sentir renovado(a) e com mais qualidade de vida. Não deixe o cuidado com você para depois! Agende já o seu horário e presenteie-se com o bem-estar que você merece. 🌿💖🌿💆‍♀️",
    online: true,
    videoCount: 5,
    postedAgo: "Há 3 horas",
    delay: "delay-3",
    cardOrder: 3,
  },
  {
    slug: "anny-cabral-aju",
    name: "Anny Cabral",
    city: "Aracaju",
    state: "SE",
    neighborhood: "Coroa do Meio",
    gender: "Feminino",
    attends: "Homens",
    paymentMethods: ["PIX", "Dinheiro"],
    schedule: "12h às 23h",
    comments: 6,
    views: 5430,
    viewsToday: 14,
    announcedSince: "10 meses",
    updatedAt: "há 1 hora",
    noSexualInteraction: true,
    whatsapp: "5579988709008",
    whatsappDisplay: "79 98870-9008",
    profilePhoto: "/assets/whatsapp-image-2026-02-20-at-1_48d22c4db28f.webp",
    gallery: [
      { type: "photo", url: "/assets/whatsapp-image-2026-02-20-at-1_48d22c4db28f.webp" },
      { type: "photo", url: "/assets/agata-capa0405_b1f62b6526d3.webp" },
      { type: "photo", url: "/assets/img_1396_5134059c329a.webp" },
    ],
    description:
      "💫 Anny Cabral — atendimento exclusivo na Coroa do Meio. Massagem sensitive, relaxante e tântrica num ambiente sofisticado e privativo. Vagas limitadas por dia para garantir qualidade e exclusividade. Reserve seu horário pelo WhatsApp.",
    online: true,
    videoCount: 0,
    postedAgo: "Há 3 horas",
    delay: "delay-4",
    cardOrder: 4,
  },
  {
    slug: "ray-aju",
    name: "Ray Massoterapeuta",
    city: "Aracaju",
    state: "SE",
    neighborhood: "Treze de Julho",
    gender: "Feminino",
    attends: "Homens, Mulheres",
    paymentMethods: ["Cartão de Crédito", "PIX", "Dinheiro"],
    schedule: "09h às 21h",
    comments: 9,
    views: 7340,
    viewsToday: 18,
    announcedSince: "1 ano 2 meses",
    updatedAt: "há 30 minutos",
    noSexualInteraction: true,
    whatsapp: "5579988709008",
    whatsappDisplay: "79 98870-9008",
    profilePhoto: "/assets/ray-massoterapeuta_c745ad6158b1.webp",
    gallery: [
      { type: "photo", url: "/assets/ray-massoterapeuta_c745ad6158b1.webp" },
      { type: "video", vimeoId: "20972562", vimeoHash: "e6cf03be96" },
      { type: "photo", url: "/assets/heloisaferraz-capa1211_2bad55f9a76b.webp" },
      { type: "video", vimeoId: "25546879", vimeoHash: "10de44524b" },
      { type: "photo", url: "/assets/agata-capa0405_b1f62b6526d3.webp" },
    ],
    description:
      "🌸 Ray Massoterapeuta — especialista em técnicas integrativas: nuru, tântrica e relaxante. Atendimento em local discreto no Treze de Julho. Cada sessão é única, pensada para o seu bem-estar e relaxamento profundo. Marque seu horário com antecedência.",
    online: true,
    videoCount: 4,
    postedAgo: "Há 14 horas",
    delay: "delay-5",
    cardOrder: 5,
  },
  {
    slug: "deusa-maya-aju",
    name: "Deusa Maya",
    city: "Aracaju",
    state: "SE",
    neighborhood: "Jardins",
    gender: "Feminino",
    attends: "Homens, Casais",
    paymentMethods: ["Cartão de Crédito", "Cartão de Débito", "PIX", "Dinheiro"],
    schedule: "10h às 23h",
    comments: 18,
    views: 14760,
    viewsToday: 52,
    announcedSince: "2 anos",
    updatedAt: "há 8 minutos",
    noSexualInteraction: true,
    whatsapp: "5579988709008",
    whatsappDisplay: "79 98870-9008",
    profilePhoto: "/assets/whatsapp-image-2026-04-28-at-1_460c980ee5ed.webp",
    gallery: [
      { type: "photo", url: "/assets/whatsapp-image-2026-04-28-at-1_460c980ee5ed.webp" },
      { type: "video", vimeoId: "25546879", vimeoHash: "10de44524b" },
      { type: "photo", url: "/assets/whatsapp-image-2026-05-07-at-1_c0e99e981931.webp" },
      { type: "photo", url: "/assets/img_3601_b06a0c98e448.webp" },
      { type: "video", vimeoId: "29158045", vimeoHash: "66046799a3" },
      { type: "photo", url: "/assets/samanta-massagens130125_e128889fee88.webp" },
    ],
    description:
      "👑 A Deusa Maya recebe você num espaço sofisticado nos Jardins, com técnicas que despertam todos os sentidos. Massagem tântrica, nuru e a 4 mãos. Reserve seu encontro com antecedência — atendimento por hora marcada apenas.",
    online: true,
    videoCount: 6,
    postedAgo: "Há 15 horas",
    delay: "delay-6",
    cardOrder: 6,
  },
  {
    slug: "amanda-vasconcelos-mcz",
    name: "Amanda Vasconcelos",
    city: "Maceió",
    state: "AL",
    neighborhood: "Jatiúca",
    gender: "Feminino",
    attends: "Homens",
    paymentMethods: ["PIX", "Dinheiro"],
    schedule: "13h às 22h",
    comments: 3,
    views: 3120,
    viewsToday: 8,
    announcedSince: "6 meses",
    updatedAt: "há 2 horas",
    noSexualInteraction: true,
    whatsapp: "5582988709008",
    whatsappDisplay: "82 98870-9008",
    profilePhoto: "/assets/20718_57d5002442e3.webp",
    gallery: [
      { type: "photo", url: "/assets/20718_57d5002442e3.webp" },
      { type: "photo", url: "/assets/heloisaferraz-capa1211_2bad55f9a76b.webp" },
    ],
    description:
      "🌷 Amanda Vasconcelos — toque suave e atendimento atencioso na Jatiúca. Especialista em massagem relaxante e sensitive. Ambiente reservado, climatizado e com toda a estrutura para você relaxar.",
    online: true,
    videoCount: 0,
    postedAgo: "Há 15 horas",
    delay: "delay-1",
    cardOrder: 7,
  },
  {
    slug: "agatha-mcz",
    name: "Ágatha Massoterapeuta",
    city: "Maceió",
    state: "AL",
    neighborhood: "Pajuçara",
    gender: "Feminino",
    attends: "Homens, Mulheres",
    paymentMethods: ["Cartão de Crédito", "PIX", "Dinheiro"],
    schedule: "09h às 22h",
    comments: 11,
    views: 9180,
    viewsToday: 24,
    announcedSince: "1 ano 5 meses",
    updatedAt: "há 1 hora",
    noSexualInteraction: true,
    whatsapp: "5582988709008",
    whatsappDisplay: "82 98870-9008",
    profilePhoto: "/assets/agata-capa0405_b1f62b6526d3.webp",
    gallery: [
      { type: "photo", url: "/assets/agata-capa0405_b1f62b6526d3.webp" },
      { type: "video", vimeoId: "20784267", vimeoHash: "bafedaddf9" },
      { type: "photo", url: "/assets/tm---agata-massoterapeuta_a0bffc5fd6af.jpg" },
      { type: "photo", url: "/assets/heloisaferraz-capa1211_2bad55f9a76b.webp" },
    ],
    description:
      "✨ Ágatha — toque sútil de verdade. Profissional formada em massoterapia com mais de 4 anos de mercado em Maceió. Atendimento à domicílio, hotel ou em espaço próprio na Pajuçara. Tântrica, nuru e relaxante.",
    online: true,
    videoCount: 3,
    postedAgo: "Há 18 horas",
    delay: "delay-2",
    cardOrder: 8,
  },
  {
    slug: "suyane-morais-for",
    name: "Suyane Morais",
    city: "Fortaleza",
    state: "CE",
    neighborhood: "Aldeota",
    gender: "Feminino",
    attends: "Homens",
    paymentMethods: ["PIX", "Dinheiro"],
    schedule: "10h às 22h",
    comments: 5,
    views: 4280,
    viewsToday: 12,
    announcedSince: "8 meses",
    updatedAt: "há 3 horas",
    noSexualInteraction: true,
    whatsapp: "5585988709008",
    whatsappDisplay: "85 98870-9008",
    profilePhoto: "/assets/img_1396_5134059c329a.webp",
    gallery: [
      { type: "photo", url: "/assets/img_1396_5134059c329a.webp" },
      { type: "photo", url: "/assets/agata-capa0405_b1f62b6526d3.webp" },
    ],
    description:
      "🌟 Suyane Morais — atendimento na Aldeota, ambiente discreto e refinado. Massagem relaxante, sensitive e tântrica. Atendimento de hora marcada — mande mensagem antes para confirmar disponibilidade.",
    online: true,
    videoCount: 0,
    postedAgo: "Há 21 horas",
    delay: "delay-3",
    cardOrder: 9,
  },
  {
    slug: "isla-ferreira-rec",
    name: "Isla Ferreira",
    city: "Recife",
    state: "PE",
    neighborhood: "Boa Viagem",
    gender: "Feminino",
    attends: "Homens, Mulheres",
    paymentMethods: ["Cartão de Crédito", "Cartão de Débito", "PIX", "Dinheiro"],
    schedule: "09h às 23h",
    comments: 8,
    views: 6890,
    viewsToday: 19,
    announcedSince: "1 ano 3 meses",
    updatedAt: "há 45 minutos",
    noSexualInteraction: true,
    whatsapp: "5581988709008",
    whatsappDisplay: "81 98870-9008",
    profilePhoto: "/assets/img_3601_b06a0c98e448.webp",
    gallery: [
      { type: "photo", url: "/assets/img_3601_b06a0c98e448.webp" },
      { type: "video", vimeoId: "20972562", vimeoHash: "e6cf03be96" },
      { type: "photo", url: "/assets/heloisaferraz-capa1211_2bad55f9a76b.webp" },
      { type: "video", vimeoId: "20784267", vimeoHash: "bafedaddf9" },
    ],
    description:
      "💎 Isla Ferreira — massoterapeuta em Boa Viagem, Recife. Especialista em técnicas asiáticas: nuru, tailandesa e tântrica. Ambiente sofisticado, com toda discrição. Reservas via WhatsApp.",
    online: true,
    videoCount: 2,
    postedAgo: "Há 21 horas",
    delay: "delay-4",
    cardOrder: 10,
  },
  {
    slug: "extase-do-toque-mcz",
    name: "Êxtase do Toque",
    city: "Maceió",
    state: "AL",
    neighborhood: "Cruz das Almas",
    gender: "Feminino",
    attends: "Homens, Casais",
    paymentMethods: ["PIX", "Dinheiro"],
    schedule: "11h às 23h",
    comments: 7,
    views: 5980,
    viewsToday: 16,
    announcedSince: "11 meses",
    updatedAt: "há 4 horas",
    noSexualInteraction: true,
    whatsapp: "5582988709008",
    whatsappDisplay: "82 98870-9008",
    profilePhoto: "/assets/whatsapp-image-2026-03-28-at-1_000a11af5eb2.webp",
    gallery: [
      { type: "photo", url: "/assets/whatsapp-image-2026-03-28-at-1_000a11af5eb2.webp" },
      { type: "photo", url: "/assets/samanta-massagens130125_e128889fee88.webp" },
    ],
    description:
      "🔥 Êxtase do Toque — atendimento de luxo na Cruz das Almas. Massagem sensitive, mútua e nuru voyeur para casais. Atendimento exclusivo, com agenda limitada para preservar a qualidade.",
    online: true,
    videoCount: 0,
    postedAgo: "Há 22 horas",
    delay: "delay-5",
    cardOrder: 11,
  },
  {
    slug: "samanta-mcz",
    name: "Samanta",
    city: "Maceió",
    state: "AL",
    neighborhood: "Mangabeiras",
    gender: "Feminino",
    attends: "Homens, Mulheres",
    paymentMethods: ["Cartão de Crédito", "PIX", "Dinheiro"],
    schedule: "10h às 22h",
    comments: 14,
    views: 11240,
    viewsToday: 31,
    announcedSince: "1 ano 11 meses",
    updatedAt: "há 1 hora",
    noSexualInteraction: true,
    whatsapp: "5582988709008",
    whatsappDisplay: "82 98870-9008",
    profilePhoto: "/assets/samanta-massagens130125_e128889fee88.webp",
    gallery: [
      { type: "photo", url: "/assets/samanta-massagens130125_e128889fee88.webp" },
      { type: "video", vimeoId: "29158045", vimeoHash: "66046799a3" },
      { type: "photo", url: "/assets/agata-capa0405_b1f62b6526d3.webp" },
      { type: "video", vimeoId: "25546879", vimeoHash: "10de44524b" },
      { type: "photo", url: "/assets/heloisaferraz-capa1211_2bad55f9a76b.webp" },
    ],
    description:
      "🌹 Samanta — atendimento de qualidade nas Mangabeiras. Massagem tântrica, com finalização e relaxante. Ambiente acolhedor, com toda estrutura para uma experiência completa de bem-estar.",
    online: true,
    videoCount: 4,
    postedAgo: "Há 1 dia",
    delay: "delay-6",
    cardOrder: 12,
  },
];

export const getMassagistaBySlug = (slug: string) =>
  MASSAGISTAS.find((m) => m.slug === slug);
